services:
  runtime:
    image: dl-workshop
    mem_limit: 16G # TODO
    shm_size: 16G # TODO
  runtime-jupyter:
    image: dl-workshop
    mem_limit: 128G # TODO
    shm_size: 128G # TODO
    command: "bash -c 'source /repo/.devcontainer/create_user_dirs.sh; source /repo/.devcontainer/jupyter_server.sh'"
    ports:
      - "8888:8888"
