services:
  runtime:
    image: dl-workshop
    mem_limit: 16G # TODO
    shm_size: 16G # TODO
    # command: "bash -c 'cd /repo && python3 -m workshop.qwen2_stresstest && tail -f /dev/null'"
    volumes:
      - /mnt/workshop:/host
  runtime-jupyter:
    image: dl-workshop
    mem_limit: 128G # TODO
    shm_size: 128G # TODO
    command: "bash -c 'source /repo/bash/create_user_dirs.sh; source /repo/bash/jupyter_server.sh'"
    ports:
      - "8888:8888"
    volumes:
      - /mnt/workshop:/host
