FROM registry.risc-software.at/risc_ds/risc_dse/dl-workshop:latest

RUN python3 -m pip install -U black

# ENTRYPOINT ["tail", "-f", "/dev/null"]  # does not work with docker run -d
CMD ["tail", "-f", "/dev/null"]
