services:
  runtime:
    image: dl-workshop
    mem_limit: 16G # TODO
    shm_size: 16G # TODO
  runtime-jupyter:
    image: dl-workshop
    mem_limit: 128G # TODO
    shm_size: 128G # TODO
    command: "bash -c 'source /repo/.devcontainer/create_user_dirs.sh; source /repo/.devcontainer/jupyter_server.sh'"
    ports:
      - "8888:8888"
  dev:
    # image: huggingface/transformers-pytorch-gpu:latest
    image: dl-workshop-dev
    # TODO: uncomment for ramdrive
    # tmpfs:
    #   - /ramdrive:size=100G
    # container_name: dl-workshop-dev
    # TODO: uncomment for GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    mem_limit: 128G # TODO
    shm_size: 128G
    volumes:
      - ../:/repo
