services:
  dev:
    image: risclidse/dl-workshop
    # TODO: Enter your username or set the shell variable in .bashrc
    container_name: dl-workshop-$SHORTUSER-devcontainer
    # Uncomment for ramdrive
    # tmpfs:
    #   - /ramdrive:size=100G
    # Uncomment for GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities:
    #             - gpu
    mem_limit: 128G # TODO
    shm_size: 128G
    command: >
      bash -c "cd /repo &&
              tail -f /dev/null"
    volumes:
      - ../:/repo
      - /mnt/workshop:/host
