services:
  runtime:
    image: dl-workshop
    shm_size: 200G
  dev:
    # TODO: specify your image here
    # image: huggingface/transformers-pytorch-gpu:latest
    image: dl-workshop-dev
    # TODO: uncomment for ramdrive
    # tmpfs:
    #   - /ramdrive:size=100g
    # container_name: dl-workshop-dev
    # TODO: uncomment for GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities:
    #             - gpu
    shm_size: 200G
    # TODO: Add mounts
    volumes:
      - ../:/repo
    command: "bash -c 'source /repo/.devcontainer/entrypoint.sh'"
    ports:
      - "8888:8888"
