services:
  dev:
    image: registry.risc-software.at/risc_ds/risc_dse/dl-workshop-dev
    # image: dl-workshop-dev
    # TODO: uncomment for ramdrive
    # tmpfs:
    #   - /ramdrive:size=100G
    # container_name: dl-workshop-dev-1
    # TODO: uncomment for GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities:
    #             - gpu
    mem_limit: 128G # TODO
    shm_size: 128G
    volumes:
      - ../:/repo
      - /mnt/workshop:/host
